## Numpy Basics

In [11]:
import time

import numpy as np

In [ ]:
arr_1d = np.array([1,2,3,4,5])
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[ 2  4  6]
 [ 8 10 12]]


### List v/s Numpy Array

In [ ]:
start_time = time.perf_counter()

list_py = [i*2 for i in range(10000000)]

end_time = time.perf_counter()

print(f"List creation takes {(end_time-start_time):.4f} seconds")

List creation takes 12.9695 seconds


In [ ]:
start_time = time.perf_counter()

np_array = np.arange(10000000)*2

end_time = time.perf_counter()

print(f"Numpy Array creation takes {(end_time-start_time):.4f} seconds")

Numpy Array creation takes 2.0395 seconds


In [ ]:
# Matrices

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix.ndim)

tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])
print(tensor)

2
int64


#### Generating Pattern

In [24]:
arr = np.ones((5,5),dtype="int64")
arr[1:4,1:4] = 0
arr[2,2] = 9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
