### Numpy Operation


In [1]:
import numpy as np

In [5]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr_2d[0,1])

2


##### Sorting


In [ ]:
unsorted_arr = np.array([3, 1, 8, 3, 10, 5, 3, 7, 2])
print(np.sort(unsorted_arr))

#2-D Array
unsorted_arr_2d = np.array([[3, 2, 3], [9, 7, 6], [10, 2, 9]])
# Row wise sorting
print(np.sort(unsorted_arr_2d,axis=1))

#Whole sorting
print(np.sort(unsorted_arr_2d,axis=None).reshape(unsorted_arr_2d.shape))


[ 1  2  3  3  3  5  7  8 10]
[[ 2  3  3]
 [ 6  7  9]
 [ 2  9 10]]
[[ 2  2  3]
 [ 3  6  7]
 [ 9  9 10]]


#### Filtering

In [ ]:
nums = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mask = nums % 2 == 0
print(nums[mask])

print(nums[nums > 5])

[2 4 6 8]
[6 7 8 9]


In [26]:
## Fancy Indexing

indices = [0, 4, 5]
print(nums[indices])

# where
where_result = np.where(nums > 2)

print(nums[where_result])

[1 5 6]
[3 4 5 6 7 8 9]


In [27]:
condition_array = np.where(nums > 5, nums * 3, nums * 2)
print(condition_array)

[ 2  4  6  8 10 18 21 24 27]


In [28]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
combined = np.concatenate((arr1,arr2))
print(combined)

[1 2 3 4 5 6]


#### Array Compatibility

In [29]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([9,1,2,3,4])
print(arr1.shape == arr2.shape)

True


In [32]:
original_arr = [[1,2,3],[4,5,6],[7,8,9]]
# Row addition
new_rows = [[10,11,12],[13,14,15]]

new_v_arr = np.vstack((original_arr,new_rows))
print(new_v_arr)

# column addition

new_col = [[7],[8],[10]]

new_c_arr = np.hstack((original_arr,new_col))
print(new_c_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]
[[ 1  2  3  7]
 [ 4  5  6  8]
 [ 7  8  9 10]]
